<?php
$lowStockProducts = $block->getLowStockProducts();
if (empty($lowStockProducts)) :
    ?>
    <p>No products are low in stock.</p>
<?php else : ?>
    <table border="1" cellpadding="5" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Product ID</th>
            <th>Name</th>
            <th>Remaining Quantity</th>
            <th>Stock ID</th>
            <th>Store ID</th>
            <th>Website ID</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($lowStockProducts as $_item) : ?>
            <tr>
                <td><?= $_item['id'] ?></td>
                <td><?= $_item['product_id'] ?></td>
                <td><?= $_item['name'] ?></td>
                <td><?= $_item['remaining_quantity'] ?></td>
                <td><?= $_item['stock_id'] ?></td>
                <td><?= $_item['store_id'] ?></td>
                <td><?= $_item['website_id'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
